name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Make example html document
      run: make html

    - name: Run check
      run: make check

    - name: Make example pdf document
      run: make pdf

    - name: Run check_pdf
      run: make check_pdf
