name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.10

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Make example document
      run: make

    - name: Run check
      run: make check
